- name: Restore selected backup
  ansible.builtin.debug:
    msg: "restoring from /backup/{{ rollback_date }}/{{ inventory_hostname }}.txt"

- name: Restore the config
  junipernetworks.junos.junos_config:
    update: replace
    src: "/tmp/{{ rollback_date }}/{{ inventory_hostname }}.txt"

- name: Print to terminal window
  ansible.builtin.debug:
    msg: "Restore is complete for device {{ inventory_hostname }} is set to {{ rollback_date }} timestamp"
