# https://github.com/ansible/ansible/issues/61183
- name: Retrieve juniper junos info
  junipernetworks.junos.junos_facts:
    gather_subset: min
    gather_network_resources: "{{ network_resources }}"
